before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - "386"
    ignore:
      - goos: windows
        goarch: arm64
    main: ./main.go
    binary: pvcusage
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: binary
    format: binary
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

release:
  draft: false
  prerelease: false
  mode: replace
  header: |
    ## Release {{ .Version }}
    
    ### Available Binaries
    
    #### Linux
    - `pvcusage_linux_amd64` (64-bit)
    - `pvcusage_linux_386` (32-bit)
    - `pvcusage_linux_arm64` (ARM 64-bit)
    
    #### macOS
    - `pvcusage_darwin_amd64` (Intel)
    - `pvcusage_darwin_arm64` (Apple Silicon)
    
    #### Windows
    - `pvcusage_windows_amd64.exe` (64-bit)
    - `pvcusage_windows_386.exe` (32-bit)
    
    SHA256 checksums are available in `checksums.txt`
    
    ---
    *Automatically generated by GoReleaser*
  version: {{ .Version }}
  tags:
    - latest
